### ISSUE TITLE
Guid values

### ISSUE THREAD

**Issue by brenwebber** [zachsaw/Binaron.Serializer#26]
I was wondering if there was any way to convert Guid values?

I've tried using an object with guid properties as well as the object with its properties stored as a Dictionary<string, object> but in both instances the Guids don't work properly. 

The object is deserialized with empty Guids, and the dictionary has ExpandoObject values in place of the Guids.

I've had to resort to obj->Json->UTF8 byte[] which has poor performance in comparison.

**Comment by zachsawcs** [comment]
Ah my bad. Completely forgot about the Guid type. I'll implement support for that in the next release!

Cheers.

**Comment by brenwebber** [comment]
Thanks Zach. 

With the arrival of .net 5.0, and with it the removal of the BinaryFormatter, I have a feeling a lot of people will be coming this way ;)

**Comment by zachsawcs** [comment]
Oh I didn't realise the BinaryFormatter's been removed in .net 5.0. That's a good heads up.

Interestingly I found a couple more places I could optimise the performance further when looking into implementing Guid support.

**Comment by brenwebber** [comment]
That's great news.

The BinaryFormatter is still available through a package import, but not included in the framework. Read more [here](https://github.com/dotnet/runtime/issues/29976) for reasons, it's quite interesting.

**Comment by zachsawcs** [comment]
To be honest I haven't used the BinaryFormatter since the early days of .Net Frameworks 1.0/2.0. It's been frowned upon by everyone if you try to use it and for good reasons too. It's too brittle and as I've just discovered from the link above, security is an even more major concern.

Anyway, I've just released a new version with Guid support. Give it a try and let me know if it works for you.

**Comment by zachsawcs** [comment]
btw if you're wondering, the optimisation I mentioned earlier was worth about 5% on benchmark 2. I should probably update Readme at some point because Binaron.Serializer is now comfortably more than 400% in both serialisation and deserialisation vs both Newtonsoft and System.Text.Json instead of 300%/350%.

**Comment by zachsaw** [comment]
Since I haven't heard back from you, I guess it's working now? I'll close the ticket for now but reach out if you find any problems.
